### ISSUE TITLE
feature pre-calculation code cannot produce a result

### ISSUE THREAD

**Issue by Gaotianhong** [huangzhii/nuclei.io#1]
Thanks for your great work.  
When running feature pre-calculation code, it stopped just before the `Stardist stage 3: deep learning feature extraction finished` and no patches were saved.
I suspect it might be due to multithreading. Could you please figure out the reason.

**Comment by huangzhii** [comment]
Hi @Gaotianhong, thanks for using our software and codebase. Can you be more specific, and preferably have some error logs or screenshots? There is no issue on my side.

**Comment by Gaotianhong** [comment]
Thanks for your response, I switched to another server to reproduce the issue, but found that the result was normal.
